### PR TITLE
run partprobe to find partitions inside cryptdev

### PR DESCRIPTION
**Pull request by fauno**
i'm not using lvm, just partitioning with fdisk over a luks partition, so i have to run partprobe (from `parted` package) for the kernel to find them :)

### CODE REVIEW

**Comment by grazzolini** [comment]
Can you explain me a little more about your setup? I never needed run partprobe from within the initramfs, regardless of lvm or not.

**Comment by fauno** [comment]
sure, it's like this on a kvm guest:

* /dev/vda2 is a luks partition
* /dev/mapper/system is the luks partition while open
* /dev/mapper/systemX are mbr partitions inside the luks partition

the latter won't appear until i run `partprobe /dev/mapper/system`.

-- 
 D

**Comment by grazzolini** [comment]
If I understood correctly, you have several partition tables, is that right? I never saw this kind of setup, and I don't know what are the implications of having two partition tables on the same disk.

I know that the device mapper possibly allows for this kind of weird situation, but I don't personally think you need nor it's even advisable that you have two partition tables on the same disk. I'll try to replicate your setup later.

**Comment by fauno** [comment]
the second partition table is inside the luks dev, instead of lvm (i've
had loss of data with lvm+luks before, so i wanted to try luks only)

**Comment by grazzolini** [comment]
Don't get me wrong, you can do all kind of crazy things with the device mapper. I personally never had any loss on lvm on luks setups, I don't know if your loss was on luks on lvm or lvm on luks.

Either way, this seems to me like a very edge case. Even though I don't think that running partprobe would harm anything, this could easily be achieved by a more generic hook, post decryption. You could call it partprobe or something like this and put it after the encryptssh hook. I'm closing this for now.

**Comment by fauno** [comment]
no problem, i just thought it could be useful to others :)

-- 
P)

**Pull request closed without merging**
